<Project>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PublishDir Condition="'$(PublishDir)' == ''">$(MSBuildThisFileDirectory)artifacts\$(Configuration)\Mod\</PublishDir>
    <UnityProjectDir Condition="'$(UnityProjectDir)' == ''">$(MSBuildThisFileDirectory)ShipbreakerVrUnity</UnityProjectDir>
    <UnityManagedDir Condition="'$(UnityManagedDir)' == ''">$(UnityProjectDir)\Build\ShipbreakerVrUnity_Data\Managed</UnityManagedDir>
    <GameManagedDir Condition="'$(GameManagedDir)' == '' and '$(GameDir)' != ''">$(GameDir)\Shipbreaker_Data\Managed</GameManagedDir>
  </PropertyGroup>
</Project>
