<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyTitle>ShipbreakerVrPatcher</AssemblyTitle>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(PublishDir)BepInEx\patchers\ShipbreakerVrPatcher\</OutputPath>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="Mono.Cecil">
      <HintPath>..\ShipbreakerVr\ModFiles\BepInEx\core\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Content Include="CopyToGame\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
